// automatically generated by the FlatBuffers compiler, do not modify

package DeviceData;

@SuppressWarnings("unused")
public final class SensorValue {
  private SensorValue() { }
  public static final byte NONE = 0;
  public static final byte FloatValue = 1;
  public static final byte IntValue = 2;
  public static final byte StringValue = 3;
  public static final byte BoolValue = 4;

  public static final String[] names = { "NONE", "FloatValue", "IntValue", "StringValue", "BoolValue", };

  public static String name(int e) { return names[e]; }
}

